### ISSUE TITLE
Training abschließen soll Farbe ändern

### ISSUE THREAD

**Issue by AndreasNatter** [Mewgrammer/SetShape#6]
Wenn Training bzw Übung fertig ist, soll die Schaltfläche grün werden

**Comment by AxelVogl** [comment]
Übung wird grün, aber erst nach gewisser Zeit. Oder nachdem man zurück zur Tagesübersicht ist und wieder in den Tag gegangen ist? Ich weiß nicht genau, wird aber auf jeden Fall grün. 
Aber wäre dann auch cool wenn der Tag, wenn alle Übungen des Tages abgeschlossen sind, auch grün wird.

**Comment by Mewgrammer** [comment]
https://github.com/Mewgrammer/SetShape/commit/b0385187504bb492ba62789719181d557d5579d0
