### ISSUE TITLE
Training erstellen

### ISSUE THREAD

**Issue by AndreasNatter** [Mewgrammer/SetShape#8]
Wenn man einen Tag hinzufügt, wird beim Dialog "ok" der Tag bereits hinzugefügt und nicht erst bei "hinzufügen" --> Tag wird doppelt

**Comment by Mewgrammer** [comment]
Das war ein Feature Request von Axel, da der klick auf "Tag hizufügen" eigentlich überflüssig ist - Evtl. sollte man allerdings die Inputs clearen wenn der Tag hinzugefügt wurde

**Comment by Mewgrammer** [comment]
https://github.com/Mewgrammer/SetShape/commits/external_db
